apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  labels:
    app: kafka
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  KAFKA_NUM_PARTITIONS: "3"
  KAFKA_DEFAULT_REPLICATION_FACTOR: "1"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_LOG_RETENTION_HOURS: "168"
  KAFKA_HEAP_OPTS: "-Xms256m -Xmx256m"
  # Zookeeper config
  ZOOKEEPER_CLIENT_PORT: "2181"
  ZOOKEEPER_TICK_TIME: "2000"
  ZOOKEEPER_HEAP_OPTS: "-Xms128m -Xmx128m"
