apiVersion: v1
kind: Namespace
metadata:
  name: greenhouse-prod
  labels:
    app.kubernetes.io/name: greenhouse
    app.kubernetes.io/part-of: greenhouse-management-system
    environment: production
