apiVersion: v1
kind: ConfigMap
metadata:
  name: service-discovery-config
  labels:
    app: service-discovery
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SERVER_PORT: "8761"
  EUREKA_SERVER_ENABLE_SELF_PRESERVATION: "false"
  EUREKA_INSTANCE_HOSTNAME: "service-discovery"
  LOGGING_LEVEL_ROOT: "INFO"
