apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  labels:
    app: greenhouse
type: Opaque
data:
  # Base64 encoded development credentials
  # postgres-env-password: postgres
  postgres-env-password: cG9zdGdyZXM=
  # postgres-ctrl-password: postgres  
  postgres-ctrl-password: cG9zdGdyZXM=
