apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway-pdb
  labels:
    app: api-gateway
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: environnement-service-pdb
  labels:
    app: environnement-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: environnement-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: controle-service-pdb
  labels:
    app: controle-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: controle-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  labels:
    app: frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend
