apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-ctrl-config
  labels:
    app: postgres-ctrl
data:
  POSTGRES_DB: controle_db
  POSTGRES_USER: postgres
  PGDATA: /var/lib/postgresql/data/pgdata
