apiVersion: v1
kind: ConfigMap
metadata:
  name: controle-service-config
  labels:
    app: controle-service
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SERVER_PORT: "8082"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-ctrl:5432/controle_db"
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "10"
  SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: "2"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery:8761/eureka/"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  LOGGING_LEVEL_ROOT: "INFO"
