apiVersion: v1
kind: Secret
metadata:
  name: environnement-service-secret
  labels:
    app: environnement-service
type: Opaque
data:
  # Base64 encoded "postgres"
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=
  SPRING_DATASOURCE_PASSWORD: cG9zdGdyZXM=
