apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-config
  labels:
    app: config-server
data:
  SPRING_PROFILES_ACTIVE: "native,kubernetes"
  SERVER_PORT: "8888"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery:8761/eureka/"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  LOGGING_LEVEL_ROOT: "INFO"
