apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-env-config
  labels:
    app: postgres-env
data:
  POSTGRES_DB: environnement_db
  POSTGRES_USER: postgres
  PGDATA: /var/lib/postgresql/data/pgdata
